import { StudioInject } from "@/components";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Kajo Studio | Studio",
  description: "Generated by create next app",
};

const Studio = () => {
  return (
    <main>
      <StudioInject />
    </main>
  );
};

export default Studio;
