import { HeroSection, HomeInject } from "@/components";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Kajo Studio | Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="">
      <HomeInject />
    </div>
  );
}
